### ISSUE TITLE
Unterminated string starting (on line 11)

### ISSUE THREAD

**Issue by MacDork** [rahulisaac/draft2fgu#1]
First:  thank you for creating this.  It's fantastic, and greatly appreciated!  I've converted maybe 6 maps so far, and I've loved the results.

I just created a new map in DungeonDraft 0.9.4.4 and got the following error when I tried to convert a `.dd2vtt` file

~~~
Exception has occurred: JSONDecodeError
Unterminated string starting at: line 1430 column 11 (char 14885)
  File "/<path>/draft2fgu/draft2fgu.py", line 11, in convert_to_fgu
    file = load(f)
  File "/<path>/draft2fgu/draft2fgu.py", line 135, in <module>
    convert_to_fgu(filename,input_path,output_path,portal_width,portal_length)
~~~

Any thoughts on this?  There aren't any spaces in the path or filename.

**Comment by MacDork** [comment]
Is this no longer supported?

**Comment by rahulisaac** [comment]
Hey, I'm sorry, I've had some personal stuff come up recently. I'm hoping
to take a look this weekend!

**Comment by MacDork** [comment]
No worries -- it seems to be working again.  I'm not sure what I did differently =/

I hope things work out for you and that personal stuff isn't too stressful.
