### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by alperozisik** [rahulisaac/draft2fgu#3]
Hi,
This tool will become very handy. Using it is not documented here or link to usage (such as [reddit](https://www.reddit.com/r/FantasyGrounds/comments/he3fod/i_created_a_script_to_convert_dungeondraft_los/)) is not linked

**Comment by rahulisaac** [comment]
You can find the documentation in the readme.txt!

**Comment by bmos** [comment]
I would suggest moving the contents of readme.txt into README.md.
It would be much more prominent.

**Comment by rahulisaac** [comment]
Done!
